version: "3"

services:
  app:
    image: inderharrysingh/www:${APP_VERSION:-v1}
    environment:
      - NODE_ENV=production
    expose:
      - 3000

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

networks:
  default:
    driver: bridge
