# name: CI/CD Pipeline

# on:
#   push:
#     branches: [ main ]

# env:
#   DOCKER_HUB_USERNAME: inderharrysingh
#   DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#   EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
#   AWS_REGION: us-east-1  # Change this to your AWS region

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ env.DOCKER_HUB_USERNAME }}
#         password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

#     - name: Build and push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         push: true
#         tags: ${{ env.DOCKER_HUB_USERNAME }}/www:${{ github.sha }}

#   deploy:
#     needs: build-and-push
#     runs-on: ubuntu-latest
#     steps:
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_REGION }}

#     - name: Deploy to EC2 instance
#       run: |
#         aws ssm send-command \
#           --instance-ids ${{ env.EC2_INSTANCE_ID }} \
#           --document-name "AWS-RunShellScript" \
#           --parameters commands=[
#             "cd /path/to/your/app",
#             "echo APP_VERSION=${{ github.sha }} > .env",
#             "docker-compose pull",
#             "docker-compose up -d"
#           ]